### ISSUE TITLE
Error on postPlayer()

### ISSUE THREAD

**Issue by Mwai** [jmrieger/onesignal-laravel#3]
Hey there,
I'm getting the following error when trying to add a new device

> Client error: `POST https://onesignal.com/api/v1//players` resulted in a `400 Bad Request` response:
> {"errors":["app_id not found."]}

My code is as shown below.

```
$data = [
          "language" => "en",
          "device_os" => "Windows",
          "device_type" => "7",
          "device_model" => "WebKit"
        ];
$player = OneSignal::postPlayer($data);
```

**Comment by jmrieger** [comment]
I'm pretty sure I've identified the issue, commit 08c86cc should solve it.  Before I push out a new version / tag, would you be comfortable doing some testing of the latest commit?  You can replace the contents of vendor/jmrieger/onesignal-laravel/src/OneSignalClient.php with the contents of OneSignalClient.php from the latest commit.

**Comment by Mwai** [comment]
That's cool. I'll test it out

**Comment by jmrieger** [comment]
@Mwai, excellent. Please keep us posted.

**Comment by jmrieger** [comment]
@Mwai, were you able to test out the last commit?

**Comment by Mwai** [comment]
Yes, I was able to test it out and it works great.

**Comment by jmrieger** [comment]
Thanks! Pushed a new version, 1.0.3, which includes these changes.
