### ISSUE TITLE
Class OneSignal not found.

### ISSUE THREAD

**Issue by NitinLogiciel** [jmrieger/onesignal-laravel#4]
I installed package and added provider and aliases as well  and run php artisan vendor:publish. When I call $response = OneSignal::getApps(); I get Class OneSignal not found. Can someone please suggest me why I am getting this error.

**Comment by vonec** [comment]
use OneSignal;

add that to the top of your class

**Comment by nitinchamola** [comment]
Thanks Vonec, It wokred. But I  have not found _namespace OneSignal;_ in any file of package. So how it is working.

**Comment by collegepaintball** [comment]
When you add the 'OneSignal' alias into your app.php file, it references the OneSignalFacade class file.  

Reference material:
https://laravel.com/docs/5.3/facades
