### ISSUE TITLE
Tags being Deprecated 

### ISSUE THREAD

**Issue by vonec** [jmrieger/onesignal-laravel#5]
can you update the class to use filters instead of tags as they are being deprecated

**Comment by ncpapaintball** [comment]
@vonec I'm seeing the note on their REST API changelog, but their docs don't appear to be updated to reflect the change that I've seen.  I sent a message to their support team, and will update this project as I hear back, and am able to.

If you happen to see any published material I'm missing, feel free to let me know and I'd be happy to update.  Chances are it would be a very easy patch, depending on how significant their change is.

**Comment by jmrieger** [comment]
@vonec I'm seeing the note on their REST API changelog, but their docs don't appear to be updated to reflect the change that I've seen. I sent a message to their support team, and will update this project as I hear back, and am able to.

If you happen to see any published material I'm missing, feel free to let me know and I'd be happy to update. Chances are it would be a very easy patch, depending on how significant their change is.

**Comment by jmrieger** [comment]
Disregard the above. I was looking intently at the players portion of the API and missed the notifications portion - their changelog was not clear on that, and their docs search doesn't index it, either.

I have asked for clarification on when exactly they'll be removing the functionality all together, but in the meantime, I'll work on a patch.

**Comment by jmrieger** [comment]
@vonec - Check out commit abe280b; that should support the filters portion of the API change.

OneSignal did reach back and state that while the tags feature is deprecated, they don't intend on removing the functionality for some time, and will give proper notice before it's disabled.

**Comment by vonec** [comment]
Thanks a lot @jmrieger

**Comment by jmrieger** [comment]
Published this commit as version 1.0.4; released on Packagist. You should be able to run `composer update` and pull in the new version.
