### ISSUE TITLE
unable to use putNotificationtrackOpen function

### ISSUE THREAD

**Issue by LtotheWT** [jmrieger/onesignal-laravel#7]
Client error: `PUT https://onesignal.com/api/v1/notifications/9220d7fd-d990-4c23-bb4b-a5e9cf079639` resulted in a `400 Bad Request` response:
{"errors":["Nothing to update. Did you mean to pass 'opened'=true?"]}

this is the error i get when i call this function
             $response = OneSignal::putNotificationTrackOpen( $id, $app_id, true );

**Comment by jmrieger** [comment]
Should be fixed with the above commit.
