### ISSUE TITLE
putPlayer required :id

### ISSUE THREAD

**Issue by hloehrmann** [jmrieger/onesignal-laravel#8]
To edit an existing player rthe REST API requires an ID.

See: https://documentation.onesignal.com/reference#edit-device

You're just calling /players which tries creating a new player object and throws an error because the device_type param is required. I think it should be something like putPlayer( $player_id, $data, $app_id ).

**Comment by jmrieger** [comment]
Not sure why I missed that in the initial version, but you're right.  I don't think the device_type param is required, but do agree that the player ID should be.  Line 396 is requiring an ID, but I don't correctly append it to the URL on line 442.  

I'll push a fix when I have a moment - probably won't be for a few days.

**Comment by hloehrmann** [comment]
Nice, thanks. I meant the device_type is currently required because it tries creating a new player instead of updating it. When updating it's not required.

**Comment by hloehrmann** [comment]
Another thing: it expects PUT, not POST and you're adding double slashes as you're appending a slash in the request method (self::API_URL . "/" . $endPoint) and in the call of the request method ($this->post("/players/", $headers);).

**Comment by hloehrmann** [comment]
Know what, I just submit some pull requests ^^

**Comment by jmrieger** [comment]
Thanks for the pulls - merged those in, and tracked down a few other bugs as well.  I'm pushing a new version out here in a few minutes - let me know if it solves your issues.
